services:
  - type: web
    buildCommand: |
      pip install -r requirements.txt
      python -c "from app import initialize_components; initialize_components()"
    startCommand: |
      python app.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
